/**
 * Image Upload API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface AddUserDTO { 
    firstName?: string;
    middleName?: string;
    lastName?: string;
    address?: string;
    nextOfKinName?: string;
    nextOfKinPhone?: string;
    dateOfBirth?: string;
    password?: string;
    email?: string;
    phoneNumber?: string;
    gender?: string;
}