/**
 * Image Upload API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ImageVM { 
    id?: number;
    description?: string;
    fileType?: string;
    fileSize?: number;
    path?: string;
    createdAt?: Date;
    lastModifiedAt?: Date;
}